# Generated by Django 4.0.3 on 2022-06-02 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='date_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('long', models.DecimalField(decimal_places=6, max_digits=16)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('long', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('appt', models.ManyToManyField(through='api.appointment', to='api.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='home_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('appt_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.date_time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='doctor_ava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.date_time')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='availablity',
            field=models.ManyToManyField(through='api.doctor_ava', to='api.date_time'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='home_appt',
            field=models.ManyToManyField(through='api.home_appointment', to='api.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appt_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.date_time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
