# Generated by Django 4.0.3 on 2022-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
    ]
