# Generated by Django 4.0.3 on 2022-06-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_doctor_is_home_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_home_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
