# Generated by Django 4.0.3 on 2022-06-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_doctor_is_home_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_appointment',
            name='appt_date',
            field=models.DateTimeField(),
        ),
    ]
