# Generated by Django 4.0.3 on 2022-06-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_end_date_date_time_start_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_time',
            old_name='end_time',
            new_name='end_date_time',
        ),
    ]
