# Generated by Django 4.0.3 on 2022-06-02 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_end_time_date_time_end_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_time',
            old_name='end_date_time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='date_time',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='date_time',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date_time',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
