# Generated by Django 4.0.3 on 2022-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_patient_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_appointment',
            name='temp',
            field=models.CharField(default='2343', max_length=70),
        ),
    ]
